### ISSUE TITLE
New version bump / jump has no binary assets

### ISSUE THREAD

**Issue by mbrancato** [chainguard-dev/melange#1644]
Previously, the melange releases at 0.14.x (e.g. [v0.14.10](https://github.com/chainguard-dev/melange/releases/tag/v0.14.10)) had built binary assets. the most recent release ([v0.15.5](https://github.com/chainguard-dev/melange/releases/tag/v0.15.5)) fails to work with [`chainguard-dev/actions/setup-melange`](https://github.com/chainguard-dev/actions/tree/main/setup-melange) because there are no binary assets on the GitHub release. Was the jump from 0.14.10 -> 0.15.5 intended and will there be new assets so that the `setup-melange` action will work again?

**Comment by xnox** [comment]
@k4leung4 @luhring can you please take a look?

**Comment by luhring** [comment]
We've cleaned up our release automation in the past few days. The latest release ([v0.15.11](https://github.com/chainguard-dev/melange/releases/tag/v0.15.11) at the time of writing) was produced from our new unified workflow, and the binary assets are intact. I expect this to remain the case for all subsequent releases, but we'll definitely jump back into the automation if something unexpected starts happening again.

**Note:** We don't intend to backfill previous releases/tags.

I'm going to close this for now, since the binary assets are there for the latest release, but we can definitely re-open this if your troubles with `setup-melange` continue!
